\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[vmargin=1in, hmargin=1in]{geometry}
\usepackage{fancyhdr, longtable, titlesec, booktabs, caption, tabularx, ragged2e}
% \usepackage{titlesec}
% \usepackage{booktabs}
\usepackage{colortbl, xcolor}
\heavyrulewidth = 2pt

% \usepackage{longtable}
% \usepackage{xcolor}


% set up title options: LARGE, Large, large, normalsize
\titleformat*{\section}{\large\bfseries}
\titleformat*{\subsection}{\normalsize\bfseries}
\titleformat*{\subsubsection}{\large\bfseries}
\titleformat*{\paragraph}{\large\bfseries}
\titleformat*{\subparagraph}{\large\bfseries}

\begin{document}
\pagestyle{fancy}

<<initialize, initialize script, cache=FALSE, results="hide", echo=FALSE, message=FALSE, tidy=TRUE>>=
source(file.path(substr(getwd(), 1,
  unlist(gregexpr(text=getwd(), pattern="LaTeX"))-2), "monthly pi.r"))
@

\lhead{Monthly Management Reports - \Sexpr{ currentMonth }}
\cfoot{CSTS Performance Improvement - Monthly Report \newline \textit{Powered by R and LaTeX}}

\section{Unsigned and Draft Documents}
Unsigned/Draft Documents by Supervisor/Enterer - Report 2004: ran \Sexpr{gsub(x=runDate, pattern="_", replace="-")} \newline
\small {
<<unsign_t1, echo=FALSE, results='asis', fig.align='left'>>=
  # table 1
    tmpDT <- unsign_table
    setnames(tmpDT, old=c("entered_by", "unsigned_draft_docs"), new=c("entered by", "unsigned/draft docs"))
    long_table(data_table=tmpDT, display="s",
             table_caption="Table 6.1",
             table_label=NULL,
               align= c("p{0.01\\textwidth}",
                        "p{0.25\\textwidth}",
                        "|p{0.27\\textwidth}",
                        "p{0.22\\textwidth}"))
@
}

\end{document}