\documentclass[a4paper]{scrartcl}
\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[table]{xcolor}
\usepackage{array}
\usepackage{pgf}
\usepackage{etoolbox}

\rowcolors{1}{white}{blue!10}

\newcounter{row}
\newcolumntype{L}{%
  >{\stepcounter{row}%
  \pgfmathtruncatemacro{\j}{int(Mod(\therow, 6))}
  \ifnum\j<3
    \global\rownum=1
  \else
    \global\rownum=0
  \fi}%
l}

\BeforeBeginEnvironment{tabular}{\setcounter{row}{0}}

\begin{document}

\section{Section}

\begin{tabular}{Lp{10cm}}
\rowcolor{blue!10}Bla1 & reference1 \\
& Description1 \\
Bla2 & reference2 \\
& Description2 \\
Bla3 & reference3 \\
& Description3 \\
Bla4 & reference4 \\
& Description4 \\
Bla5 & reference5 \\
& Description5 \\
Bla6 & reference6 \\
& Description6 \\
\end{tabular}

\end{document}